import {priceUsage,type UsageSample,type PriceBook} from './pricing';
export interface MeterEvent extends UsageSample {at:number;threadId:string;project:string}
export interface MeterScan {samples:MeterEvent[];files:number;scanned:number;pending:number;errors:number;excludedForks:number;fetchedAt:number}
export interface UsageTotals {tokens:number;input:number;output:number;cached:number;cost:number|null;unpriced:string[];unpricedCalls:number;unpricedTokens:number;calls:number;tasks:number}
export type UsagePeriod='today'|'7d'|'30d'|'month';
export interface UsagePeriodData {totals:UsageTotals;days:Array<UsageTotals&{day:string}>;projects:Array<UsageTotals&{path:string}>;models:Array<UsageTotals&{model:string}>}
export interface UsageDayDetail {models:Array<UsageTotals&{model:string}>;threads:Array<UsageTotals&{threadId:string;project:string}>}
export interface UsageOverview {details:Record<string,UsageDayDetail>;periods:Record<UsagePeriod,UsagePeriodData>;monthProjection:number|null;activeDays:number;today:UsageTotals;days:Array<UsageTotals&{day:string}>;projects:Array<UsageTotals&{path:string}>;fetchedAt:number;pending:number;errors:number;excludedForks:number;files:number;priceDate:string;priceError:boolean}
export function localDay(at:number){const d=new Date(at);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function usageStart(now=Date.now(),days=7){const d=new Date(now);d.setHours(0,0,0,0);d.setDate(d.getDate()-(days-1));return d.getTime();}
export function aggregateUsage(scan:MeterScan,book:PriceBook,now=Date.now(),priceError=false):UsageOverview{
 const events=scan.samples.filter(e=>e.at>=usageStart(now,31)&&e.at<=now&&[e.input,e.cached,e.cacheWrite,e.output,e.contextTokens].every(v=>Number.isFinite(v)&&v>=0));
 const totals=(items:MeterEvent[]):UsageTotals=>{const priced=priceUsage(items,book);return {tokens:items.reduce((s,e)=>s+e.input+e.cached+e.cacheWrite+e.output,0),input:items.reduce((s,e)=>s+e.input+e.cached+e.cacheWrite,0),cached:items.reduce((s,e)=>s+e.cached,0),output:items.reduce((s,e)=>s+e.output,0),cost:!items.length?0:priced.pricedCalls&&Number.isFinite(priced.pricedUSD)?priced.pricedUSD:null,unpriced:priced.unpriced,unpricedCalls:priced.unpricedCalls,unpricedTokens:priced.unpricedTokens,calls:items.length,tasks:new Set(items.map(e=>e.threadId)).size};};
 const byDay=new Map<string,MeterEvent[]>();for(const e of events){const day=localDay(e.at),list=byDay.get(day)??[];list.push(e);byDay.set(day,list);}
 const history:Array<UsageTotals&{day:string}>=[];for(let i=0;i<31;i++){const d=new Date(usageStart(now,31));d.setDate(d.getDate()+i);const day=localDay(d.getTime());history.push({day,...totals(byDay.get(day)??[])});}
 const aggregatePeriod=(start:number):UsagePeriodData=>{const selected=events.filter(e=>e.at>=start),groups=new Map<string,MeterEvent[]>(),models=new Map<string,MeterEvent[]>();for(const e of selected){const list=groups.get(e.project)??[];list.push(e);groups.set(e.project,list);const model=models.get(e.model)??[];model.push(e);models.set(e.model,model);}
 return {totals:totals(selected),days:history.filter(d=>d.day>=localDay(start)),projects:[...groups].map(([path,list])=>({path,...totals(list)})).sort((a,b)=>b.tokens-a.tokens).slice(0,5),models:[...models].map(([model,list])=>({model,...totals(list)})).sort((a,b)=>b.tokens-a.tokens)};};
 const monthStart=new Date(now);monthStart.setDate(1);monthStart.setHours(0,0,0,0);
 const periods={today:aggregatePeriod(usageStart(now,1)),'7d':aggregatePeriod(usageStart(now)), '30d':aggregatePeriod(usageStart(now,30)),month:aggregatePeriod(monthStart.getTime())};
 const elapsed=(now-monthStart.getTime())/86400000,monthDays=new Date(monthStart.getFullYear(),monthStart.getMonth()+1,0).getDate();
 const details:Record<string,UsageDayDetail>={};
 for(const day of history){const items=byDay.get(day.day)??[],models=new Map<string,MeterEvent[]>(),threads=new Map<string,MeterEvent[]>();for(const e of items){const m=models.get(e.model)??[];m.push(e);models.set(e.model,m);const t=threads.get(e.threadId)??[];t.push(e);threads.set(e.threadId,t);}details[day.day]={models:[...models].map(([model,list])=>({model,...totals(list)})).sort((a,b)=>b.tokens-a.tokens),threads:[...threads].map(([threadId,list])=>({threadId,project:list[0].project,...totals(list)})).sort((a,b)=>b.tokens-a.tokens)};}
 return {details,periods,monthProjection:periods.month.totals.cost===null||periods.month.totals.unpricedCalls>0||elapsed<1?null:periods.month.totals.cost/elapsed*monthDays,activeDays:history.slice(-30).filter(d=>d.calls>0).length,today:periods.today.totals,days:periods['7d'].days,projects:periods['7d'].projects,fetchedAt:scan.fetchedAt,pending:scan.pending,errors:scan.errors,excludedForks:scan.excludedForks,files:scan.files,priceDate:book.updatedAt,priceError};
}
