import {cp,mkdir,readFile,writeFile,rename,rm,symlink,access} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {trimPython} from './trim-package.mjs';
if(process.platform!=='darwin'||process.arch!=='arm64')throw Error('Current package target is macOS arm64. Windows and Intel packages need separate validation.');
const run=(bin,args)=>execFileSync(bin,args,{stdio:'inherit'});
const pkg=JSON.parse(await readFile('package.json','utf8'));
const output=resolve('release'),stage=join(output,'mac-arm64'),app=join(stage,'Cyber Overseer.app'),contents=join(app,'Contents'),resources=join(contents,'Resources'),code=join(resources,'app');
await access('assets/icon/icon.icns');
await mkdir(output,{recursive:true});
// Only generated staging is replaced; never modify an installed application.
await rm(stage,{recursive:true,force:true});await mkdir(stage,{recursive:true});
run('ditto',['node_modules/electron/dist/Electron.app',app]);
await rm(join(resources,'default_app.asar'),{force:true});
await mkdir(code,{recursive:true});
for(const name of ['dist','data'])await cp(name,join(code,name),{recursive:true});
await rm(join(code,'dist','watch.cjs'),{force:true});
await mkdir(join(code,'scripts'),{recursive:true});
await cp('scripts/usage-scan.py',join(code,'scripts','usage-scan.py'));
await writeFile(join(code,'package.json'),JSON.stringify({name:pkg.name,productName:'Cyber Overseer',version:pkg.version,main:pkg.main},null,2));
await cp('assets/icon/icon.icns',join(resources,'electron.icns'));
await cp('artifacts/runtime/python',join(resources,'python'),{recursive:true,dereference:false,verbatimSymlinks:true});
await trimPython(join(resources,'python'));
await mkdir(join(resources,'licenses'),{recursive:true});
for(const [source,name] of [['LICENSE','SOURCE-LICENSE'],['assets/ASSET-LICENSE.md','ASSET-LICENSE.md'],['node_modules/electron/dist/LICENSE','Electron-LICENSE'],['node_modules/electron/dist/LICENSES.chromium.html','Chromium-LICENSES.html'],['assets/CODEBURN-NOTICE.txt','CODEBURN-NOTICE.txt'],['node_modules/smol-toml/LICENSE','smol-toml-LICENSE']])await cp(source,join(resources,'licenses',name));
await cp('artifacts/runtime/provenance.json',join(resources,'licenses','python-provenance.json'));
await writeFile(join(resources,'licenses','PROJECT-STATUS.txt'),'Experimental preview. Source code: MIT. Original character artwork: all rights reserved; see ASSET-LICENSE.md.\nPython and its bundled dependency license texts are retained inside Resources/python.\n');
await rename(join(contents,'MacOS','Electron'),join(contents,'MacOS','Cyber Overseer'));
const plist=join(contents,'Info.plist');
for(const [key,value] of Object.entries({CFBundleExecutable:'Cyber Overseer',CFBundleName:'Cyber Overseer',CFBundleDisplayName:'Cyber Overseer',CFBundleIdentifier:'local.cyber-overseer.desktop',CFBundleShortVersionString:pkg.version,CFBundleVersion:pkg.version}))run('/usr/libexec/PlistBuddy',['-c',`Set :${key} ${value}`,plist]);
// Ad-hoc signing supports local arm64 execution; this is NOT Developer ID signing or notarization.
run('codesign',['--force','--deep','--sign','-',app]);
run('codesign',['--verify','--deep','--strict',app]);
run(join(resources,'python','bin','python3'),['-I','-B','-c','import sqlite3,sys,json,pathlib,os,time; assert sqlite3.connect(":memory:").execute("select 42").fetchone()[0] == 42; print("Bundled Python + SQLite:", sys.version.split()[0], sqlite3.sqlite_version)']);
await symlink('/Applications',join(stage,'Applications'));
const dmg=join(output,`Cyber-Overseer-${pkg.version}-mac-arm64.dmg`);
run('hdiutil',['create','-volname','Cyber Overseer','-srcfolder',stage,'-format','ULMO','-ov',dmg]);
run('hdiutil',['verify',dmg]);
await writeFile(dmg+'.sha256',createHash('sha256').update(await readFile(dmg)).digest('hex')+'  '+dmg.split('/').at(-1)+'\n');
console.log(`Local preview created: ${app}\n${dmg}\nAd-hoc signed; not notarized. Not a public release.`);
