import {usageMoney,usageShare,usageCalls} from './usage-format';
import type {UsagePeriod} from '../core/usage-overview';
let selectedPeriod:UsagePeriod='today';
let selectedDay='';
let dayOpener='';
import type {OverseerState} from '../core/model';
const el=(tag:string,text='',cls='')=>{const e=document.createElement(tag);e.textContent=text;e.className=cls;return e;};
export function renderUsageOverview(s:OverseerState,quota?:HTMLElement){
 const en=s.language==='en',u=s.usageOverview,root=el('section','','usage-section');root.append(el('h2',(en?'Usage overview':'用量总览')+(u&&(u.pending||u.errors)?(en?' · partial data':' · 部分数据'):'')));
 if(!u){if(quota)root.append(quota);root.append(el('p',s.usageError?(en?'Unable to read usage. Watching continues independently.':'暂时无法读取用量，看护仍独立运行。'):(en?'Indexing usage metadata…':'正在索引用量记录…'),'overview-muted'));return root;}
 const n=(v:number)=>Intl.NumberFormat(en?'en-US':'zh-CN',{notation:'compact',maximumFractionDigits:1}).format(v);
 const money=(v:number|null)=>usageMoney(v,en);
 const period=u.periods[selectedPeriod],current=period.totals,days=selectedPeriod==='today'?u.periods['30d'].days:period.days;
 const toolbar=el('div','','usage-toolbar'),range=el('div','','usage-range');range.setAttribute('aria-label',en?'Usage period':'用量时段');
 for(const [key,zh,english] of [['today','今日','Today'],['7d','7 天','7D'],['30d','30 天','30D'],['month','本月','Month']] as const){const b=el('button',en?english:zh);b.setAttribute('aria-pressed',String(selectedPeriod===key));b.dataset.period=key;b.dataset.overviewKey='period:'+key;b.onclick=()=>{selectedPeriod=key;selectedDay='';const next=renderUsageOverview(s,quota);root.replaceWith(next);next.querySelector<HTMLButtonElement>(`[data-period="${key}"]`)?.focus({preventScroll:true});};range.append(b);}
 toolbar.append(el('span',`${period.days[0]?.day??''} ${selectedPeriod==='today'?'':'→ '+period.days.at(-1)?.day} · Codex`),range);root.prepend(toolbar);
 const chooseDay=(day:string,opener:string)=>{selectedDay=day;dayOpener=opener;const next=renderUsageOverview(s,quota);root.replaceWith(next);const panel=next.querySelector<HTMLElement>('.usage-drill');panel?.scrollIntoView({block:'nearest'});panel?.focus({preventScroll:true});};
 const renderModels=(items:typeof period.models,totalCost:number|null)=>{const list=el('div','','usage-model-list');if(!items.length)list.append(el('p',en?'No usage recorded.':'暂无用量记录。','overview-muted'));for(const m of [...items].sort((a,b)=>(b.cost??-1)-(a.cost??-1))){const row=el('div','','usage-model-row');const share=m.cost!==null&&totalCost!==null&&totalCost>0?m.cost/totalCost*100:null;row.append(el('span',m.model),el('strong',money(m.cost)),el('small',`${n(m.tokens)} Token${share===null?'':` · ${usageShare(share)} ${en?'of cost':'费用占比'}`}`));if(share!==null){const track=el('div','','usage-model-track'),fill=el('span');fill.style.width=`${Math.min(100,share)}%`;fill.style.minWidth=share>0?'2px':'0';track.append(fill);row.append(track);}list.append(row);}return list;};
 const grid=el('div','','usage-grid'),today=el('section','','overview-card usage-today');today.append(el('h2',selectedPeriod==='today'?(en?'Today · estimated cost':'今日 · 估算费用'):(en?'Period · estimated cost':'所选时段 · 估算费用')),el('strong',money(current.cost),'usage-total'),el('p',`${en?'Input':'输入'} ${n(current.input)} · ${en?'Output':'输出'} ${n(current.output)}`,'overview-muted'),el('p',`${en?'Cached input':'缓存输入'} ${n(current.cached)}${current.input?` · ${(current.cached/current.input*100).toFixed(0)}%`:''}`,'overview-muted'),el('p',`${usageCalls(current.calls,en)} · ${current.tasks} ${en?(current.tasks===1?'active task':'active tasks'):'个活跃任务'} · ${n(current.tokens)} Token`,'usage-cost'));
 today.insertBefore(today.querySelector('.usage-cost')!,today.querySelector('.overview-muted'));
 const trend=el('section','','overview-card usage-trend');trend.append(el('h2',`${en?'Daily spend':'每日费用'} · ${days.length} ${en?'days':'天'}`));const chart=el('div','','usage-chart');const max=Math.max(0.01,...days.map(d=>d.cost??0));
 for(const d of days){const bar=el('button','','usage-day');bar.dataset.overviewKey='usage-day:'+d.day;bar.setAttribute('aria-pressed',String(selectedDay===d.day));bar.onclick=()=>chooseDay(d.day,bar.dataset.overviewKey!);if(d===days.at(-1))bar.classList.add('is-today');bar.title=`${d.day} · ${d.tokens.toLocaleString()} Token · ${money(d.cost)}`;bar.setAttribute('aria-label',bar.title);const fill=el('div','','usage-bar');if(d.cost===null)fill.classList.add('is-unpriced');fill.style.height=`${(d.cost??0)/max*140}px`;bar.append(el('small',money(d.cost)),fill,el('span',d.day.slice(5)));chart.append(bar);}trend.append(chart);const chartHint=el('p',en?'Select a day to see its models and tasks.':'点击日期，查看当天的模型与任务。','usage-chart-hint');trend.append(chartHint);for(const button of chart.querySelectorAll<HTMLButtonElement>('button')){const show=()=>{chartHint.textContent=button.title;};button.onmouseenter=show;button.onfocus=show;button.onmouseleave=()=>{if(document.activeElement!==button)chartHint.textContent=en?'Select a day to see its models and tasks.':'点击日期，查看当天的模型与任务。';};}
 const total=days.reduce((sum,d)=>sum+(d.cost??0),0),peak=days.reduce((best,d)=>(d.cost??0)>(best.cost??0)?d:best,days[0]);
 const facts=el('div','','usage-facts');
 for(const [label,value] of [[en?'Daily average':'日均',money(days.some(d=>d.cost===null)?null:total/days.length)],[en?'Peak':'峰值',days.some(d=>d.cost===null)?money(null):peak?`${money(peak.cost)} · ${peak.day.slice(5)}`:'$0.00'],[en?'Yesterday':'昨日',money(u.days.at(-2)?.cost??null)]]){const item=el('span',label);item.append(el('strong',value));facts.append(item);}trend.append(facts);
 const projects=el('section','','overview-card usage-projects');projects.append(el('h2',en?'Top projects · selected period':'项目消耗排行 · 所选时段'));
 if(!period.projects.length)projects.append(el('p',en?'No recorded usage in this period.':'该时段暂无已读取的用量。','overview-muted'));
 for(const p of period.projects){const row=el('div','','usage-project'),name=p.path.replace(/[\\/]+$/,'').split(/[\\/]/).at(-1)||p.path;row.append(el('span',name),el('strong',n(p.tokens)+' Token'),el('small',money(p.cost)));row.title=p.path;projects.append(row);}
 const activity=el('section','','overview-card usage-activity');activity.append(el('h2',en?'Daily activity · last 30 days':'每日活动 · 近 30 天'),el('strong',`${u.activeDays} ${en?(u.activeDays===1?'active day':'active days'):'个活跃日'}`,'usage-activity-total'));
 const heat=el('div','','usage-heatmap');const activityDays=u.periods['30d'].days,maxCalls=Math.max(1,...activityDays.map(d=>d.calls));
 // Monday-first calendar alignment; empty cells are outside the measured range.
 const first=new Date(activityDays[0].day+'T12:00:00'),offset=(first.getDay()+6)%7;
 for(let i=0;i<offset;i++)heat.append(el('span','','usage-heat-empty'));
 for(const d of activityDays){const cell=el('button','','usage-heat-cell');cell.dataset.overviewKey='heat-day:'+d.day;cell.setAttribute('aria-pressed',String(selectedDay===d.day));cell.onclick=()=>chooseDay(d.day,cell.dataset.overviewKey!);cell.title=`${d.day} · ${usageCalls(d.calls,en)} · ${money(d.cost)}`;cell.setAttribute('aria-label',cell.title);cell.dataset.level=String(d.calls?Math.max(1,Math.ceil(d.calls/maxCalls*4)):0);heat.append(cell);}
 activity.append(heat,el('p',`${activityDays[0].day.slice(5)} → ${activityDays.at(-1)!.day.slice(5)} · ${en?'Intensity by calls':'颜色深浅表示调用数'}`,'overview-muted'));
 const topline=el('div','','usage-topline');topline.append(today,activity);if(quota)topline.append(quota);const month=el('div','','usage-month');
 for(const [label,value] of [[en?'Month to date':'本月累计',money(u.periods.month.totals.cost)],[en?'Projected month · at current pace':'本月预测 · 按当前进度',u.monthProjection===null?(en?'Not available':'暂无预测'):money(u.monthProjection)]]){const cell=el('div');cell.append(el('span',label),el('strong',value));month.append(cell);}
 const models=el('section','','overview-card usage-models');models.append(el('h2',en?'Model spend · selected period':'模型消耗 · 所选时段'),renderModels(period.models,current.cost));
 grid.append(topline,month,trend);
 if(selectedDay&&u.details[selectedDay]){const detail=u.details[selectedDay],dayTotal=u.periods['30d'].days.find(d=>d.day===selectedDay)??u.periods.month.days.find(d=>d.day===selectedDay),drill=el('section','','overview-card usage-drill');drill.tabIndex=-1;drill.dataset.overviewKey='usage-detail';drill.setAttribute('aria-label',selectedDay+' '+(en?'usage details':'用量明细'));const head=el('div','','usage-drill-head'),close=el('button',en?'Close':'收起','quiet');close.dataset.overviewKey='usage-close';close.onclick=()=>{selectedDay='';const next=renderUsageOverview(s,quota);root.replaceWith(next);const opener=Array.from(next.querySelectorAll<HTMLElement>('[data-overview-key]')).find(e=>e.dataset.overviewKey===dayOpener);opener?.scrollIntoView({block:'nearest'});opener?.focus({preventScroll:true});};drill.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close.click();}};head.append(el('h2',selectedDay+' · '+(en?'Usage details':'用量明细')),close);drill.append(head,renderModels(detail.models,dayTotal?.cost??null),el('h2',en?'Active tasks':'活跃任务'));
 if(!detail.threads.length)drill.append(el('p',en?'No recorded usage on this day.':'当天暂无用量记录。','overview-muted'));
 for(const t of detail.threads){const task=s.tasks.find(task=>task.id===t.threadId),row=el(task?'button':'div','','usage-drill-task');row.append(el('span',task?.title??t.project.replace(/[\\/]+$/,'').split(/[\\/]/).at(-1)??t.project),el('strong',money(t.cost)),el('small',`${usageCalls(t.calls,en)} · ${n(t.tokens)} Token`));row.title=t.project+' · '+t.threadId;if(!task)row.append(el('small',en?'Historical task · details unavailable here':'历史任务 · 暂无可打开的任务详情','usage-historical'));if(task){row.dataset.overviewKey='usage-task:'+t.threadId;row.setAttribute('aria-label',(en?'Open task details: ':'打开任务详情：')+task.title);row.append(el('span','↗','usage-task-arrow'));row.onclick=()=>root.dispatchEvent(new CustomEvent('overview-task',{bubbles:true,detail:t.threadId}));}drill.append(row);}grid.append(drill);}
 grid.append(models,projects);root.append(grid);
 const notices=[en?'Estimates are not subscription charges. Calls count usage events; tasks count activity in the selected period.':'估算费用不等于订阅扣款。调用数按用量事件计数；任务数为所选时段有用量的任务。'];
 if(u.pending)notices.push(en?`${u.pending} files still indexing; totals are partial.`:`还有 ${u.pending} 个文件待索引，当前为部分统计。`);
 if(u.errors)notices.push(en?`${u.errors} files have incomplete usage.`:`${u.errors} 个文件的计量不完整。`);
 if(u.excludedForks)notices.push(en?`${u.excludedForks} forked sessions excluded to avoid replay double-counting.`:`已排除 ${u.excludedForks} 个分叉会话，避免重放重复计量。`);
 if(s.usageError)notices.push(en?'Refresh failed; showing last read.':'刷新失败，显示上次读取结果。');
 if(u.priceError)notices.push(en?'Price table unavailable; fallback rates used.':'价格表读取异常，使用后备价格。');
 const unknown=[...new Set(u.periods['30d'].days.flatMap(d=>d.unpriced))];if(unknown.length)notices.push((en?'Unpriced models: ':'未计价模型：')+unknown.join(', '));
 notices.push((en?'Updated ':'更新于 ')+new Date(u.fetchedAt).toLocaleTimeString(en?'en-US':'zh-CN'));
 root.append(el('p',notices.join(' '),'usage-notes'));return root;
}
